ministryofjustice/hmpps-change-someones-cell

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Change ingress URL to match cert

[MAP-10] Change ingress URL to match cert

---

assets/scss/application.scss
assets/scss/components/_footer.scss
assets/scss/components/_header-bar.scss
cypress.config.ts
feature.env
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
integration_tests/e2e/commonComponents.cy.ts
integration_tests/e2e/signIn.cy.ts
integration_tests/index.d.ts
integration_tests/mockApis/components.ts
integration_tests/pages/index.ts
server/app.ts
server/config.ts
server/data/feComponentsClient.test.ts
server/data/feComponentsClient.ts
server/data/index.ts
server/middleware/getFeComponents.ts
server/middleware/setUpWebSecurity.ts
server/services/feComponentsService.test.ts
server/services/feComponentsService.ts
server/services/index.ts
server/utils/nunjucksSetup.ts
server/views/partials/footer.njk
server/views/partials/layout.njk

Implement new header and footer as the template doeesn't automatically include it.
Based on:
https://github.com/ministryofjustice/hmpps-template-typescript/pull/227
[MAP-496]
[MAP-496]: https://dsdmoj.atlassian.net/browse/MAP-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Implement new header and footer

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

This is needed for showing the breadcrumb link

fix: Add DPS_URL env var

---

server/config.ts

I changed this in error in my last PR

fix: Change REDIS_URL env var back to REDIS_HOST

---

integration_tests/e2e/cellMoveConfirmation.cy.ts
integration_tests/pages/cellMoveConfirmationPage.ts
server/controllers/cellMove/cellMoveConfirmation.test.ts
server/controllers/cellMove/cellMoveConfirmation.ts
server/routes/cellMoveRouter.ts
server/views/cellMove/cellMoveHomepage.njk
server/views/cellMove/confirmation.njk
server/views/partials/layout.njk

Confirmation page
[MAP-681]
[MAP-681]: https://dsdmoj.atlassian.net/browse/MAP-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-681] Confirmation page

---

integration_tests/e2e/spaceCreated.cy.ts
integration_tests/pages/spaceCreatedPage.ts
server/controllers/cellMove/spaceCreated.test.ts
server/controllers/cellMove/spaceCreated.ts
server/routes/cellMoveRouter.ts
server/routes/changeSomeonesCellRouter.ts
server/views/cellMove/spaceCreated.njk

[MAP-681] Space created

---

integration_tests/e2e/cellNotAvailable.cy.ts
integration_tests/pages/cellNotAvailablePage.ts
server/controllers/cellMove/cellNotAvailable.test.ts
server/controllers/cellMove/cellNotAvailable.ts
server/routes/cellMoveRouter.ts
server/views/cellMove/cellNotAvailable.njk

Cell not available page
[MAP-681]
[MAP-681]: https://dsdmoj.atlassian.net/browse/MAP-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-681] Cell not available page

---

integration_tests/e2e/cellMoveViewResidentialLocation.cy.ts
server/controllers/cellMove/cellMoveViewResidentialLocation.test.ts
server/controllers/cellMove/cellMoveViewResidentialLocation.ts
server/data/prisonApiClient.test.ts
server/data/prisonApiClient.ts
server/data/whereaboutsApiClient.test.ts
server/data/whereaboutsApiClient.ts
server/routes/changeSomeonesCellRouter.ts
server/services/locationService.test.ts
server/services/locationService.ts
server/services/prisonerCellAllocationService.ts
server/views/cellMove/cellMoveViewResidentialLocation.njk

View residential location page
[MAP-658]
[MAP-658]: https://dsdmoj.atlassian.net/browse/MAP-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-658] View residential location page

---

integration_tests/e2e/viewOffenderDetails.cy.ts
integration_tests/pages/offenderDetailsPage.ts
server/controllers/cellMove/viewOffenderDetails.test.ts
server/controllers/cellMove/viewOffenderDetails.ts
server/data/prisonApiClient.test.ts
server/data/prisonApiClient.ts
server/routes/cellMoveRouter.ts
server/services/prisonerDetailsService.test.ts
server/services/prisonerDetailsService.ts
server/views/cellMove/offenderDetails.njk

[MAP-661] Prisoner details page

---

integration_tests/e2e/cellMoveTemporaryMove.cy.ts
server/controllers/cellMove/cellMoveTemporaryMove.test.ts
server/controllers/cellMove/cellMoveTemporaryMove.ts
server/routes/changeSomeonesCellRouter.ts
server/views/cellMove/cellMoveTemporaryMove.njk

Temporary move page
[MAP-659]
[MAP-659]: https://dsdmoj.atlassian.net/browse/MAP-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-659] Temporary move page

---

server/controllers/cellMove/cellMoveTemporaryMove.test.ts
server/controllers/cellMove/cellMoveViewResidentialLocation.test.ts
server/controllers/cellMove/confirmCellMove.test.ts
server/views/cellMove/cellMoveTemporaryMove.njk
server/views/cellMove/cellMoveViewResidentialLocation.njk

fix: Update some wrong links

---

cypress.config.ts
integration_tests/e2e/cellMoveHistory.cy.ts
integration_tests/e2e/recentCellMoves.cy.ts
integration_tests/mockApis/prisonApi.ts
server/controllers/cellMove/cellMoveHistory.test.ts
server/controllers/cellMove/cellMoveHistory.ts
server/controllers/cellMove/recentCellMoves.test.ts
server/controllers/cellMove/recentCellMoves.ts
server/data/prisonApiClient.test.ts
server/data/prisonApiClient.ts
server/routes/changeSomeonesCellRouter.ts
server/services/prisonerCellAllocationService.test.ts
server/services/prisonerCellAllocationService.ts
server/services/prisonerDetailsService.test.ts
server/services/prisonerDetailsService.ts
server/services/userService.test.ts
server/services/userService.ts
server/utils.ts
server/views/cellMove/cellMoveHistory.njk
server/views/cellMove/recentCellMoves.njk

Recent cell move pages
[MAP-660]
[MAP-660]: https://dsdmoj.atlassian.net/browse/MAP-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-660] Recent cell move pages

---

integration_tests/e2e/cellMoveConfirmation.cy.ts
server/app.ts
server/controllers/backToStart.test.ts
server/controllers/backToStart.ts
server/controllers/cellMove/cellMoveViewResidentialLocation.test.ts
server/controllers/cellMove/cellMoveViewResidentialLocation.ts
server/middleware/returnUrl.test.ts
server/middleware/returnUrl.ts
server/routes/index.ts

Back to start button
[MAP-740]
[MAP-740]: https://dsdmoj.atlassian.net/browse/MAP-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-740] Back to start button

---

integration_tests/e2e/receptionConfirmMove.cy.ts
integration_tests/pages/receptionConfirmMovePage.ts
server/controllers/cellMove/confirmReceptionMove.test.ts
server/controllers/cellMove/confirmReceptionMove.ts
server/routes/receptionMoveRouter.ts
server/views/receptionMove/confirmReceptionMove.njk

Confirm cell move (reception) page
[MAP-679]
[MAP-679]: https://dsdmoj.atlassian.net/browse/MAP-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-679] Confirm cell move (reception) page

---

integration_tests/e2e/receptionConfirmation.cy.ts
integration_tests/e2e/receptionConsiderRisks.cy.ts
integration_tests/pages/receptionConfirmationPage.ts
server/controllers/cellMove/confirmationReception.test.ts
server/controllers/cellMove/confirmationReception.ts
server/routes/receptionMoveRouter.ts
server/views/receptionMove/confirmation.njk

Confirmation page (reception)
[MAP-682]
[MAP-682]: https://dsdmoj.atlassian.net/browse/MAP-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-682] Confirmation page (reception)

---

integration_tests/e2e/receptionConfirmMove.cy.ts
integration_tests/e2e/receptionConsiderRisks.cy.ts
integration_tests/e2e/searchForCell.cy.ts
server/controllers/cellMove/receptionFull.test.ts
server/controllers/cellMove/receptionFull.ts
server/routes/receptionMoveRouter.ts
server/views/receptionMove/receptionFull.njk

Reception full page
and re-enable all skipped integration tests
[MAP-678]
[MAP-678]: https://dsdmoj.atlassian.net/browse/MAP-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-678] Reception full page

---

helm_deploy/hmpps-change-someones-cell/values.yaml
helm_deploy/values-prod.yaml

Prisons and private prisons to be restricted to prod access only
DEV abd Pre for internal users

MAP-907 prisons allow list for prod only

---

server/utils/azureAppInsights.ts

This will allow us to track the behaviour of users across the estate and to identify trends for prisons.
Copied from Prisoner Profile project.
[MAP-950]
[MAP-950]: https://dsdmoj.atlassian.net/browse/MAP-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add username and agency to Application Insights telemetry

---

server/utils/azureAppInsights.ts

They are very spammy and we don't need to know about them.
[MAP-950]
[MAP-950]: https://dsdmoj.atlassian.net/browse/MAP-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAP-950] Stop sending /metrics and /ping paths to Applications Insights

---

cypress.config.ts
feature.env
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
integration_tests/e2e/considerRisks.cy.ts
integration_tests/e2e/searchForCell.cy.ts
integration_tests/e2e/selectCell.cy.ts
integration_tests/mockApis/prisonerSearchApi.ts
package-lock.json
package.json
server/config.ts
server/controllers/cellMove/cellMoveHistory.test.ts
server/controllers/cellMove/cellMovePrisonerSearch.test.ts
server/controllers/cellMove/cellMoveTemporaryMove.test.ts
server/controllers/cellMove/cellMoveViewResidentialLocation.test.ts
server/controllers/cellMove/confirmCellMove.test.ts
server/controllers/cellMove/confirmReceptionMove.test.ts
server/controllers/cellMove/considerRisks.test.ts
server/controllers/cellMove/considerRisksReception.test.ts
server/controllers/cellMove/recentCellMoves.test.ts
server/controllers/cellMove/selectCell.test.ts
server/controllers/cellMove/selectCell.ts
server/data/index.ts
server/data/prisonApiClient.ts
server/data/prisonerSearchApiClient.test.ts
server/data/prisonerSearchApiClient.ts
server/services/index.ts
server/services/prisonerCellAllocationService.test.ts
server/services/prisonerCellAllocationService.ts

We have been spamming the Prison API and causing it to fall over. To avoid that problem, we now use the Prisoner Search API to do a bulk lookup of the inmates in a list of cells.
[MAP-969]
[MAP-969]: https://dsdmoj.atlassian.net/browse/MAP-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-969 WIP - move prisoner location lookup to search 

---

package-lock.json
package.json

chore: Remove unused HTTP logger library

---

server/config.ts

Related to SDIT-924 Lock check PUT /api/bookings/{bookingId}/living-unit/{internalLocationDescription}

---

package-lock.json

Bump axios and micromatch to fix CVEs
MAP-1603

MAP-1603: Bump axios and micromatch to fix CVEs

---

CHANGELOG.md
package-lock.json
package.json
server/middleware/setUpCsrf.ts

copying the set up on template project

MAP-1855 replace csurf with csrf-sync

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
package-lock.json
package.json

to align with typescript project
see   [Moving to Node 22 by andrewrlee · Pull Request #474 · ministryofjustice/hmpps-template-typescript](https://github.com/ministryofjustice/hmpps-template-typescript/pull/474/files)

MAP-1866 update to node V22

---

package-lock.json
package.json

just to redeploy to prod to pickup new IP ingress (for private prison Parc)

Map 1963 update non-breaking dependencies
