ministryofjustice/hmpps-change-someones-cell

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
It's not a probation thing so .prison is more appropriate
[MAP-10]
[MAP-10]: https://dsdmoj.atlassian.net/browse/MAP-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Rename domain to use .prison instead of .hmpps

- server/controllers/cellMove/cellMoveHomepage.ts
We decided that there shouldn't be a `change-someones-cell` in the URL path. Also the establishment roll card should link to the main DPS app.
> fix: Use correct link hrefs on menu page

- server/app.ts
- server/controllers/cellMove/cellMovePrisonerSearch.test.ts
- server/controllers/cellMove/cellMovePrisonerSearch.ts
- server/controllers/images.ts
- server/middleware/getFeComponents.ts
- server/middleware/populateClientToken.ts
- server/services/prisonerCellAllocationService.ts
The original DPS app uses user creds for some API calls and system client creds for others, but the latest advice is to use system client creds for everything.
[MAP-632]
[MAP-632]: https://dsdmoj.atlassian.net/browse/MAP-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-632] Use system client creds for API calls as per latest advice

- integration_tests/e2e/searchForCell.cy.ts
- integration_tests/e2e/selectCell.cy.ts
These tests were skipped because the pages didn't exist yet, but now they do.
> Enable skipped integration tests

- server/app.ts
- server/data/feComponentsClient.ts
- server/middleware/currentUser.ts
- server/middleware/getFeComponents.ts
- server/services/feComponentsService.test.ts
- server/services/feComponentsService.ts
This makes sure that the caseload shown in the header matches the active caseload that the app is aware of!
See discussion:
https://mojdt.slack.com/archives/C69NWE339/p1706794247306949?thread_ts=1706793461.544379&cid=C69NWE339
[MAP-683]
[MAP-683]: https://dsdmoj.atlassian.net/browse/MAP-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-683] Get active caseload from frontend components API metadata if possible

- helm_deploy/hmpps-change-someones-cell/values.yaml
Getting a Privacy error in UI. 
Need to ensure the tls cert name matches that in cloud platform namespace
> MAP-794 changed tlsSecretName

- assets/scss/local.scss
as it was creating  a large space above footer
> MAP-894 remove override of govuk-wrapper class 

- package-lock.json
- package.json
- server/app.ts
This should stop it crashing pods when API calls fail. It should show the standard error page instead of an NginX 502 bad gateway error page.
[MAP-960]
[MAP-960]: https://dsdmoj.atlassian.net/browse/MAP-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-960] Use express-async-errors

- server/monitoring/metricsApp.ts
We are getting out of memory errors and it may be because Prometheus has a bucket in memory for every possible path for every prison number. This config change should replace all prisoner numbers in paths with '#val'.
[MAP-1257]
[MAP-1257]: https://dsdmoj.atlassian.net/browse/MAP-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-1257] Normalise prison numbers in metrics

- Dockerfile
For some reason this isn't installed by default. We need to be able to use `ps` on the command line in order to diagnose a memory leak.
[MAP-1257]
[MAP-1257]: https://dsdmoj.atlassian.net/browse/MAP-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-1257] Install procps in container image

- cypress.config.ts
- feature.env
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/mockApis/locationsInsidePrisonApi.ts
- server/config.ts
- server/controllers/cellMove/cellMoveConfirmation.test.ts
- server/controllers/cellMove/cellMoveHistory.test.ts
- server/controllers/cellMove/cellMoveViewResidentialLocation.test.ts
- server/controllers/cellMove/confirmCellMove.test.ts
- server/controllers/cellMove/considerRisks.test.ts
- server/controllers/cellMove/searchForCell.test.ts
- server/controllers/cellMove/selectCell.test.ts
- server/controllers/cellMove/viewCellSharingRiskAssessment.test.ts
- server/data/index.ts
- server/data/locationsInsidePrisonApiClient.test.ts
- server/data/locationsInsidePrisonApiClient.ts
- server/data/whereaboutsApiClient.test.ts
- server/data/whereaboutsApiClient.ts
- server/services/index.ts
- server/services/locationService.test.ts
- server/services/locationService.ts
swap to get internal location **Group** data from new locationsInsidePrisonApi instead of whereaboutsApi
endpoint called in whereabouts was /agencies/${agencyId}/locations/groups
endpoint in new locationsInsidePrisonApi is /locations/prison/${prisonId}/groups
MAP-1267 investigation has identified that locations that had  a single child location had their 'children' reduced to an empty array in prison-api. As we want to replicate this in our service but without it being dictated by the new locationsInsidePrisonApi, the reduction has been done in the CSC UI app.
> MAP-1030 get internal location data from new locationsInsidePrisonApi

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
So that we stop spamming the main `#dps_alerts` channel
[MAP-1257]
[MAP-1257]: https://dsdmoj.atlassian.net/browse/MAP-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-1257] Configure Prometheus to send alerts to our own channel

- server/controllers/cellMove/selectCell.test.ts
- server/controllers/cellMove/selectCell.ts
.. when there are zero locations
This is fix for a 400 error that arises when we attempt to get prisoners at a location without providing a list of locations.
> MAP-1283 prevent call to get the prisoners at a location..

- server/middleware/populateClientToken.ts
Avoid instantiating a new Redis client every time the populateClientToken middleware runs to try and fix the memory leak and 500 response code issues
> [MAP-1257] Avoid instantiating a new Redis client every time the populateClientToken middleware runs

- cypress.config.ts
- integration_tests/e2e/cellMoveConfirmation.cy.ts
- integration_tests/e2e/confirmCellMove.cy.ts
- integration_tests/e2e/considerRisks.cy.ts
- integration_tests/e2e/selectCell.cy.ts
- integration_tests/mockApis/locationsInsidePrisonApi.ts
- integration_tests/mockApis/prisonApi.ts
- server/controllers/cellMove/cellMoveConfirmation.test.ts
- server/controllers/cellMove/cellMoveConfirmation.ts
- server/controllers/cellMove/confirmCellMove.test.ts
- server/controllers/cellMove/confirmCellMove.ts
- server/controllers/cellMove/considerRisks.test.ts
- server/controllers/cellMove/considerRisks.ts
- server/controllers/cellMove/selectCell.test.ts
- server/controllers/cellMove/selectCell.ts
- server/data/locationsInsidePrisonApiClient.test.ts
- server/data/locationsInsidePrisonApiClient.ts
- server/data/prisonApiClient.test.ts
- server/data/prisonApiClient.ts
- server/services/locationService.test.ts
- server/services/locationService.ts
- server/services/prisonerCellAllocationService.test.ts
- server/services/prisonerCellAllocationService.ts
- server/views/cellMove/selectCell.njk
This code is the first of a series of changes to phase out calls to prisonApi in favour of the new locationsInsideprisonApi. The code below replaces the call to   prisonApi  /api/locations/{locationId} which gets location data, with a call to the new locationsInsidePrisonApi /locations/key/{key}
**The cellId passed as a query string has changed from the nomisId to the string representation of cell location**
prisonApi calls rely on an integer value for the location id. However locationsInsidePrisonApi has no mapping with that integer value so we've decided to use the /locations/key/{key} endpoint which uses the location value like MDI-A-1-1.
Using the location string value like MDI-1-1-1 has a knock on impact across many pages. The id (cellId) is passed between pages as a query string. …
> Map 1350 csc replacing prison api calls with locations api 1

- server/controllers/cellMove/cellMoveHistory.test.ts
- server/controllers/cellMove/cellMovePrisonerSearch.test.ts
- server/controllers/cellMove/cellMoveTemporaryMove.test.ts
- server/controllers/cellMove/cellMoveViewResidentialLocation.test.ts
- server/controllers/cellMove/confirmCellMove.test.ts
- server/controllers/cellMove/confirmReceptionMove.test.ts
- server/controllers/cellMove/considerRisks.test.ts
- server/controllers/cellMove/considerRisks.ts
- server/controllers/cellMove/considerRisksReception.test.ts
- server/controllers/cellMove/recentCellMoves.test.ts
- server/controllers/cellMove/selectCell.test.ts
- server/services/index.ts
- server/services/locationService.test.ts
- server/services/locationService.ts
- server/services/prisonerCellAllocationService.test.ts
- server/services/prisonerCellAllocationService.ts
moving getInmatesAtLocation() to the prisonerCellAllocationService module as per the PR comments on [this](https://github.com/ministryofjustice/hmpps-change-someones-cell/pull/73)
> MAP-1350 move getInmatesAtLocation() to a more appropriate service

- cypress.config.ts
- integration_tests/e2e/confirmCellMove.cy.ts
- integration_tests/e2e/spaceCreated.cy.ts
- integration_tests/mockApis/prisonApi.ts
- server/controllers/cellMove/confirmCellMove.test.ts
- server/data/prisonApiClient.test.ts
- server/data/prisonApiClient.ts
- server/services/locationService.test.ts
- server/services/locationService.ts
call to locationService.getAttributesForLocation() and hence prisonApi.getAttributesForLocation() has already been removed [see this line 102 of server/controllers/cellMove/confirmCellMove.ts](https://github.com/ministryofjustice/hmpps-change-someones-cell/pull/73) , but the actual methods and tests were not. This code change is to remove those dangling functions too.
> MAP-1350 remove call to prisonApiClient.getAttributesForLocation 

- assets/js/govukFrontendInit.js
- assets/js/index.js
- package.json
- server/utils/nunjucksSetup.ts
- server/views/partials/layout.njk
changes made to how the govuk-frontend is implemented and to be be inline with other projects (specifically [this](https://github.com/ministryofjustice/hmpps-prisoner-profile/pull/416)) rather the typescript template project. This is because the template project also introduces changes to the build process including using the esbuild module. Implementing these build changes to be done as a separate ticket
> MAP-1403 refactor implementation of latest govuk-frontend dependency

- integration_tests/e2e/selectCell.cy.ts
- server/controllers/cellMove/confirmCellMove.ts
- server/controllers/cellMove/selectCell.test.ts
- server/controllers/cellMove/selectCell.ts
- server/data/locationsInsidePrisonApiClient.ts
- server/views/cellMove/selectCell.njk
- Updates the cell selection process to prefer 'actualCapacity', which considers both 'workingCapacity' and 'maxCapacity', over 'maxCapacity' alone. This makes sure that any operational changes to cell capacity are reflected in selection process. The updates were made in the relevant controller, view, and test files.
- Introduces a filter in the selection of cells to exclude the current cell of the prisoner. Previously, the selectedCells array included the prisoner's own cell, which is not necessary as the purpose is to find potential cells to move the prisoner to, excluding their current one. This not only delivers a more accurate list of cells but also reduces the potential for user selection errors.
> MAP-1414 Replace maxCapacity with actualCapacity in cell selection

- Dockerfile
Previous PR to update Node to v22 failed at build-docker stage because the python install and build wasn't correct. 
Error suggested using   python-is-python3 2to3
> MAP-1866 fix dockerfile

- helm_deploy/hmpps-change-someones-cell/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-prod.yaml
'Internal' allow list group now deprecated. 
Using digital_staff_and_mojo and  moj_cloud_platform instead, as per  hmpps-ip-allowlists github repo instructions
> MAP-2541 add HMP Kilco allowlist group for dev only
